#ifndef _GUI_PALLETE_H
#define _GUI_PALLETE_H

#include <stdint.h>
#include <string.h>

enum GuiColor {
	DEFAULT_DESKTOP = 0x55aaaa,
    WINDOW_FILL = 0xFFFFFF,
    WINDOW_BORDER = 0xc0c7c8,
    WINDOW_BORDER_OUTLINE = 0x000000,
    WINDOW_TITLE_ACTIVE = 0x0000aa,
    WINDOW_TITLE_INACTIVE = 0xc3c7cb,
    WINDOW_TITLE_TEXT_INACTIVE = 0x000000,
    WINDOW_TITLE_TEXT_ACTIVE = 0xFFFFFF,
};

#endif /* _GUI_PALLETE_H */
